server:
  port: 8001
  servlet:
    context-path: /

spring:
  application:
    name: springcloud-dept-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.101.90:3306/springcloud01?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  instance:
    instance-id: springcloud-dept-provider-8001 #自定义服务名称信息
    prefer-ip-address: true #访问路径显示IP信息
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com/eureka/,http://eureka7003.com:7003/eureka
#      defaultZone: http://localhost:7001/eureka/

# eureka info内容
info:
  app.name: springcloud
  company.name: www.springcloud.com
  build.artifactId: springcloud-dept-provider-8001
  build.version: 0.0.1-SNAPSHOT
